/**
 * THE ICON SET, AS PIXEL ART.
 *
 * Every glyph is 16 rows of 16 characters:
 *
 *   "."  transparent
 *   "x"  ink, full strength
 *   "o"  ink at half strength, for a second tone inside one colour
 *
 * WHY A CHARACTER GRID RATHER THAN SVG PATHS. The previous icons were 24x24
 * strokes with round caps at 2.5px - a perfectly good web-app idiom, and
 * completely wrong for chunky pixel art: a stroked path antialiases, so at any
 * size the "pixels" have soft grey edges. These are rectangles on an integer
 * grid, and they are drawn with shapeRendering="crispEdges", so an icon is made
 * of the same hard pixels the game world is.
 *
 * Being able to READ the picture in the source is the point. A young player
 * could redraw one of these by typing an x, which is not true of "M12 2L3 9.5".
 *
 * THE SIZE RULE. A glyph is 16 units wide, so it must be rendered at a multiple
 * of 16 CSS pixels. At 24px each glyph pixel would be 1.5 screen pixels and
 * adjacent pixels would come out 1px and 2px wide alternately - which looks
 * subtly broken in a way that passes every automated check. SIZE.iconLarge and
 * SIZE.iconSmall exist as multiples of 16 for exactly this reason, and Icon.tsx
 * warns in development if it is handed anything else.
 */

export type IconName =
  | "pencil"
  | "eraser"
  | "rect"
  | "start"
  | "finish"
  | "undo"
  | "redo"
  | "fit"
  | "zoomIn"
  | "zoomOut"
  | "grid"
  | "map"
  | "play"
  | "stop"
  | "save"
  | "folder"
  | "trash"
  | "download"
  | "upload"
  | "rename"
  | "sparkle"
  | "close"
  | "tick"
  | "left"
  | "right"
  | "up"
  | "down"
  | "expand"
  | "sound"
  | "mute"
  | "help"
  | "keyboard"
  | "gamepad"
  | "hand";

/** Rows and columns per glyph. Do not change without redrawing every glyph. */
export const GRID = 16;

export const GLYPHS: Readonly<Record<IconName, readonly string[]>> = {
  pencil: [
    "................",
    "..........xxxx..",
    ".........xxxxx..",
    "........xxxxx...",
    ".......xxxxx....",
    "......xxxxx.....",
    ".....xxxxx......",
    "....xxxxx.......",
    "...xxxxx........",
    "..xxxxx.........",
    "..xxxx..........",
    "..oxxx..........",
    "..oox...........",
    "..oo............",
    "................",
    "................",
  ],
  eraser: [
    "................",
    "................",
    "................",
    "....xxxxxxxx....",
    "...xxxxxxxxxx...",
    "...xxxxxxxxxx...",
    "...xxxxxxxxxx...",
    "...oooooooooo...",
    "...oooooooooo...",
    "...oooooooooo...",
    "....oooooooo....",
    "................",
    "................",
    "................",
    "................",
    "................",
  ],
  rect: [
    "................",
    "................",
    "..xxxxxxxxxxxx..",
    "..xxxxxxxxxxxx..",
    "..xx........xx..",
    "..xx..oooo..xx..",
    "..xx..oooo..xx..",
    "..xx..oooo..xx..",
    "..xx..oooo..xx..",
    "..xx........xx..",
    "..xxxxxxxxxxxx..",
    "..xxxxxxxxxxxx..",
    "................",
    "................",
    "................",
    "................",
  ],
  start: [
    "................",
    "...xx...........",
    "...xxxxxxxxxx...",
    "...xxxxxxxxxx...",
    "...xxxxxxxx.....",
    "...xxxxxxxx.....",
    "...xxxxxx.......",
    "...xxxxxx.......",
    "...xxxx.........",
    "...xx...........",
    "...xx...........",
    "...xx...........",
    "...xx...........",
    "..xxxxxx........",
    "..xxxxxx........",
    "................",
  ],
  finish: [
    "................",
    "...xx...........",
    "...xxxxooxxooxx.",
    "...xxxxooxxooxx.",
    "...xxooxxooxxoo.",
    "...xxooxxooxxoo.",
    "...xxxxooxxooxx.",
    "...xxxxooxxooxx.",
    "...xxooxxooxxoo.",
    "...xxooxxooxxoo.",
    "...xx...........",
    "...xx...........",
    "...xx...........",
    "..xxxxxx........",
    "..xxxxxx........",
    "................",
  ],
  undo: [
    "................",
    "................",
    "......xx........",
    ".....xxx........",
    "....xxx.........",
    "...xxx..........",
    "..xxxxxxxxxxx...",
    "..xxxxxxxxxxx...",
    "..xxxxxxxxxxx...",
    "...xxx..........",
    "....xxx.........",
    ".....xxx........",
    "......xx........",
    "................",
    "................",
    "................",
  ],
  redo: [
    "................",
    "................",
    "........xx......",
    "........xxx.....",
    ".........xxx....",
    "..........xxx...",
    "...xxxxxxxxxxx..",
    "...xxxxxxxxxxx..",
    "...xxxxxxxxxxx..",
    "..........xxx...",
    ".........xxx....",
    "........xxx.....",
    "........xx......",
    "................",
    "................",
    "................",
  ],
  fit: [
    "................",
    "..xxxxx..xxxxx..",
    "..xxxxx..xxxxx..",
    "..xx........xx..",
    "..xx........xx..",
    "..xx........xx..",
    "................",
    "......oooo......",
    "......oooo......",
    "................",
    "..xx........xx..",
    "..xx........xx..",
    "..xx........xx..",
    "..xxxxx..xxxxx..",
    "..xxxxx..xxxxx..",
    "................",
  ],
  zoomIn: [
    "................",
    "...xxxxxxx......",
    "..xx.....xx.....",
    ".xx...x...xx....",
    ".xx...x...xx....",
    ".xx.xxxxx.xx....",
    ".xx...x...xx....",
    ".xx...x...xx....",
    "..xx.....xx.....",
    "...xxxxxxx......",
    "........xxx.....",
    ".........xxx....",
    "..........xxx...",
    "...........xx...",
    "................",
    "................",
  ],
  zoomOut: [
    "................",
    "...xxxxxxx......",
    "..xx.....xx.....",
    ".xx.......xx....",
    ".xx.......xx....",
    ".xx.xxxxx.xx....",
    ".xx.......xx....",
    ".xx.......xx....",
    "..xx.....xx.....",
    "...xxxxxxx......",
    "........xxx.....",
    ".........xxx....",
    "..........xxx...",
    "...........xx...",
    "................",
    "................",
  ],
  grid: [
    "................",
    "................",
    "..xxxxx..xxxxx..",
    "..xxxxx..xxxxx..",
    "..xxxxx..xxxxx..",
    "..xxxxx..xxxxx..",
    "..xxxxx..xxxxx..",
    "................",
    "................",
    "..ooooo..ooooo..",
    "..ooooo..ooooo..",
    "..ooooo..ooooo..",
    "..ooooo..ooooo..",
    "..ooooo..ooooo..",
    "................",
    "................",
  ],
  map: [
    "................",
    "................",
    "..xxxx..........",
    "..xxxx.oooo.....",
    "..xxxx.oooo.xxxx",
    "..xxxx.oooo.xxxx",
    "..xxxx.oooo.xxxx",
    "..xxxx.oooo.xxxx",
    "..xxxx.oooo.xxxx",
    "..xxxx.oooo.xxxx",
    "..xxxx.oooo.xxxx",
    "..xxxx.oooo.xxxx",
    "..xxxx.oooo.....",
    ".......oooo.....",
    "................",
    "................",
  ],
  play: [
    "................",
    "................",
    "....xx..........",
    "....xxxx........",
    "....xxxxxx......",
    "....xxxxxxxx....",
    "....xxxxxxxxxx..",
    "....xxxxxxxxxx..",
    "....xxxxxxxx....",
    "....xxxxxx......",
    "....xxxx........",
    "....xx..........",
    "................",
    "................",
    "................",
    "................",
  ],
  stop: [
    "................",
    "................",
    "................",
    "...xxxxxxxxxx...",
    "...xxxxxxxxxx...",
    "...xxxxxxxxxx...",
    "...xxxxxxxxxx...",
    "...xxxxxxxxxx...",
    "...xxxxxxxxxx...",
    "...xxxxxxxxxx...",
    "...xxxxxxxxxx...",
    "...xxxxxxxxxx...",
    "...xxxxxxxxxx...",
    "................",
    "................",
    "................",
  ],
  save: [
    "................",
    "................",
    ".......xx.......",
    ".......xx.......",
    ".......xx.......",
    ".......xx.......",
    "....xxxxxxxx....",
    ".....xxxxxx.....",
    "......xxxx......",
    ".......xx.......",
    "................",
    "..oo........oo..",
    "..oo........oo..",
    "..oooooooooooo..",
    "..oooooooooooo..",
    "................",
  ],
  folder: [
    "................",
    "................",
    "..xxxxx.........",
    "..xxxxxx........",
    "..xxxxxxxxxxxx..",
    "..xxxxxxxxxxxx..",
    "..oooooooooooo..",
    "..oooooooooooo..",
    "..oooooooooooo..",
    "..oooooooooooo..",
    "..oooooooooooo..",
    "..oooooooooooo..",
    "..xxxxxxxxxxxx..",
    "................",
    "................",
    "................",
  ],
  trash: [
    "................",
    "......xxxx......",
    "..xxxxxxxxxxxx..",
    "..xxxxxxxxxxxx..",
    "................",
    "...xxxxxxxxxx...",
    "...xx.xxxx.xx...",
    "...xx.xxxx.xx...",
    "...xx.xxxx.xx...",
    "...xx.xxxx.xx...",
    "...xx.xxxx.xx...",
    "...xx.xxxx.xx...",
    "...xxxxxxxxxx...",
    "................",
    "................",
    "................",
  ],
  download: [
    "................",
    ".......xx.......",
    ".......xx.......",
    ".......xx.......",
    ".......xx.......",
    ".......xx.......",
    "..xx...xx...xx..",
    "...xx..xx..xx...",
    "....xxxxxxxx....",
    ".....xxxxxx.....",
    "......xxxx......",
    ".......xx.......",
    "................",
    "..oooooooooooo..",
    "..oooooooooooo..",
    "................",
  ],
  upload: [
    "................",
    ".......xx.......",
    "......xxxx......",
    ".....xxxxxx.....",
    "....xxxxxxxx....",
    "...xx..xx..xx...",
    "..xx...xx...xx..",
    ".......xx.......",
    ".......xx.......",
    ".......xx.......",
    ".......xx.......",
    ".......xx.......",
    "................",
    "..oooooooooooo..",
    "..oooooooooooo..",
    "................",
  ],
  rename: [
    "................",
    "...xxxxxxxxxx...",
    "...xxxxxxxxxx...",
    ".......xx.......",
    ".......xx.......",
    ".......xx.......",
    ".......xx.......",
    ".......xx.......",
    ".......xx.......",
    ".......xx.......",
    ".......xx.......",
    "...xxxxxxxxxx...",
    "...xxxxxxxxxx...",
    "................",
    "................",
    "................",
  ],
  sparkle: [
    "................",
    ".......xx.......",
    ".......xx.......",
    "......xxxx......",
    "......xxxx......",
    "..xxxxxxxxxxxx..",
    "..xxxxxxxxxxxx..",
    "......xxxx......",
    "......xxxx......",
    ".......xx.......",
    ".......xx.......",
    "................",
    "................",
    "................",
    "................",
    "................",
  ],
  close: [
    "................",
    "................",
    "..xxx......xxx..",
    "..xxxx....xxxx..",
    "...xxxx..xxxx...",
    "....xxxxxxxx....",
    ".....xxxxxx.....",
    "......xxxx......",
    "......xxxx......",
    ".....xxxxxx.....",
    "....xxxxxxxx....",
    "...xxxx..xxxx...",
    "..xxxx....xxxx..",
    "..xxx......xxx..",
    "................",
    "................",
  ],
  tick: [
    "................",
    "................",
    "............xxx.",
    "...........xxx..",
    "..........xxx...",
    ".........xxx....",
    "..xx....xxx.....",
    "..xxx..xxx......",
    "...xxxxxx.......",
    "....xxxx........",
    ".....xx.........",
    "................",
    "................",
    "................",
    "................",
    "................",
  ],
  left: [
    "................",
    "................",
    "..........xx....",
    ".........xxx....",
    "........xxx.....",
    ".......xxx......",
    "......xxx.......",
    ".....xxx........",
    ".....xxx........",
    "......xxx.......",
    ".......xxx......",
    "........xxx.....",
    ".........xxx....",
    "..........xx....",
    "................",
    "................",
  ],
  sound: [
    "................",
    "................",
    "..........xx....",
    ".....xxx..xx.oo.",
    "....xxxx.x.x.oo.",
    "...xxxxx.x.xo.o.",
    "xxxxxxxx.x.xo.o.",
    "xxxxxxxx.x.xo.o.",
    "xxxxxxxx.x.xo.o.",
    "xxxxxxxx.x.xo.o.",
    "...xxxxx.x.xo.o.",
    "....xxxx.x.x.oo.",
    ".....xxx..xx.oo.",
    "..........xx....",
    "................",
    "................",
  ],
  mute: [
    "................",
    "................",
    "................",
    ".....xxx........",
    "....xxxx..x...x.",
    "...xxxxx...x.x..",
    "xxxxxxxx....x...",
    "xxxxxxxx...x.x..",
    "xxxxxxxx..x...x.",
    "xxxxxxxx........",
    "...xxxxx........",
    "....xxxx........",
    ".....xxx........",
    "................",
    "................",
    "................",
  ],
  expand: [
    "................",
    "..xxxxx..xxxxx..",
    "..xxxxx..xxxxx..",
    "..xx........xx..",
    "..xx..oooo..xx..",
    "..x..oooooo..x..",
    ".....oooooo.....",
    ".....oooooo.....",
    ".....oooooo.....",
    ".....oooooo.....",
    "..x..oooooo..x..",
    "..xx..oooo..xx..",
    "..xx........xx..",
    "..xxxxx..xxxxx..",
    "..xxxxx..xxxxx..",
    "................",
  ],
  right: [
    "................",
    "................",
    "....xx..........",
    "....xxx.........",
    ".....xxx........",
    "......xxx.......",
    ".......xxx......",
    "........xxx.....",
    "........xxx.....",
    ".......xxx......",
    "......xxx.......",
    ".....xxx........",
    "....xxx.........",
    "....xx..........",
    "................",
    "................",
  ],
  // The vertical pair. The set had left and right from the day it was drawn and
  // no up or down, which was fine while the only arrows were undo and redo -
  // and not fine the moment anything had to describe a d-pad.
  up: [
    "................",
    "................",
    "................",
    "................",
    "................",
    ".......xx.......",
    "......xxxx......",
    ".....xxxxxx.....",
    "....xxx..xxx....",
    "...xxx....xxx...",
    "..xxx......xxx..",
    "..xx........xx..",
    "................",
    "................",
    "................",
    "................",
  ],
  down: [
    "................",
    "................",
    "................",
    "................",
    "..xx........xx..",
    "..xxx......xxx..",
    "...xxx....xxx...",
    "....xxx..xxx....",
    ".....xxxxxx.....",
    "......xxxx......",
    ".......xx.......",
    "................",
    "................",
    "................",
    "................",
    "................",
  ],
  help: [
    "................",
    "................",
    "....xxxxxx......",
    "...xxxxxxxx.....",
    "...xxx..xxx.....",
    "........xxx.....",
    ".......xxx......",
    "......xxx.......",
    "......xxx.......",
    "......xxx.......",
    "................",
    "................",
    "......xxx.......",
    "......xxx.......",
    "................",
    "................",
  ],
  keyboard: [
    "................",
    "................",
    "................",
    "..xxxxxxxxxxxx..",
    "..x..........x..",
    "..x.oo.oo.oo.x..",
    "..x..........x..",
    "..x.oo.oo.oo.x..",
    "..x..........x..",
    "..x..oooooo..x..",
    "..x..........x..",
    "..xxxxxxxxxxxx..",
    "................",
    "................",
    "................",
    "................",
  ],
  gamepad: [
    "................",
    "................",
    "................",
    "..xxxxxxxxxxxx..",
    ".xx..........xx.",
    ".x..x......oo..x",
    ".x.xxx.........x",
    ".x..x.....oo...x",
    ".xx..........xx.",
    "..xxxxxxxxxxxx..",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
  ],
  hand: [
    "................",
    "................",
    ".......xx.......",
    ".......xx.......",
    ".......xx.......",
    ".......xx.......",
    ".......xxx.xx...",
    ".......xxxxxxx..",
    "...xx..xxxxxxx..",
    "....xxxxxxxxxx..",
    ".....xxxxxxxxx..",
    ".....xxxxxxxxx..",
    "......xxxxxxx...",
    "......xxxxxxx...",
    "................",
    "................",
  ],
};

/** One horizontal run of identical pixels: the unit an icon is drawn in. */
export interface GlyphRun {
  x: number;
  y: number;
  w: number;
  /** True for "o" - the half-strength tone. */
  soft: boolean;
}

/**
 * Collapse a glyph into horizontal runs.
 *
 * A 16x16 glyph is up to 256 rectangles drawn one pixel at a time; merging runs
 * takes a typical glyph down to 20-40. Cheap to compute and computed once per
 * glyph per session, so the saving is pure.
 */
export function glyphRuns(rows: readonly string[]): GlyphRun[] {
  const runs: GlyphRun[] = [];
  for (let y = 0; y < rows.length; y++) {
    const row = rows[y];
    let x = 0;
    while (x < row.length) {
      const ch = row[x];
      if (ch === ".") {
        x++;
        continue;
      }
      let end = x;
      while (end < row.length && row[end] === ch) end++;
      runs.push({ x, y, w: end - x, soft: ch === "o" });
      x = end;
    }
  }
  return runs;
}
